package it.studiofontanelli.jabistudio.dao;

import it.studiofontanelli.jabistudio.mybatis.entity.AbiFormsForm;
import it.studiofontanelli.jabistudio.mybatis.entity.AbiFormsFormExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AbiFormsFormDAOImpl extends SqlMapClientDaoSupport implements AbiFormsFormDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public AbiFormsFormDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public int countByExample(AbiFormsFormExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("_abi_forms_form.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public int deleteByExample(AbiFormsFormExample example) {
        int rows = getSqlMapClientTemplate().delete("_abi_forms_form.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public int deleteByPrimaryKey(Integer idField) {
        AbiFormsForm _key = new AbiFormsForm();
        _key.setIdField(idField);
        int rows = getSqlMapClientTemplate().delete("_abi_forms_form.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void insert(AbiFormsForm record) {
        getSqlMapClientTemplate().insert("_abi_forms_form.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void insertSelective(AbiFormsForm record) {
        getSqlMapClientTemplate().insert("_abi_forms_form.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public List selectByExample(AbiFormsFormExample example) {
        List list = getSqlMapClientTemplate().queryForList("_abi_forms_form.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public AbiFormsForm selectByPrimaryKey(Integer idField) {
        AbiFormsForm _key = new AbiFormsForm();
        _key.setIdField(idField);
        AbiFormsForm record = (AbiFormsForm) getSqlMapClientTemplate().queryForObject("_abi_forms_form.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public int updateByExampleSelective(AbiFormsForm record, AbiFormsFormExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("_abi_forms_form.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public int updateByExample(AbiFormsForm record, AbiFormsFormExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("_abi_forms_form.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public int updateByPrimaryKeySelective(AbiFormsForm record) {
        int rows = getSqlMapClientTemplate().update("_abi_forms_form.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public int updateByPrimaryKey(AbiFormsForm record) {
        int rows = getSqlMapClientTemplate().update("_abi_forms_form.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    protected static class UpdateByExampleParms extends AbiFormsFormExample {
        private Object record;

        public UpdateByExampleParms(Object record, AbiFormsFormExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}