package it.studiofontanelli.jabistudio.spring.dao;

import it.studiofontanelli.jabistudio.spring.entity.AbiDocksDock;
import it.studiofontanelli.jabistudio.spring.entity.AbiDocksDockExample;
import java.util.List;

public interface AbiDocksDockDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int countByExample(AbiDocksDockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int deleteByExample(AbiDocksDockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    void insert(AbiDocksDock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    void insertSelective(AbiDocksDock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    List selectByExample(AbiDocksDockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    AbiDocksDock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByExampleSelective(AbiDocksDock record, AbiDocksDockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByExample(AbiDocksDock record, AbiDocksDockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByPrimaryKeySelective(AbiDocksDock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByPrimaryKey(AbiDocksDock record);
}