package it.studiofontanelli.jabistudio.spring.dao;

import it.studiofontanelli.jabistudio.spring.entity.AbiFormsForm;
import it.studiofontanelli.jabistudio.spring.entity.AbiFormsFormExample;
import java.util.List;

public interface AbiFormsFormDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int countByExample(AbiFormsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int deleteByExample(AbiFormsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int deleteByPrimaryKey(Integer idField);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    void insert(AbiFormsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    void insertSelective(AbiFormsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    List selectByExample(AbiFormsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    AbiFormsForm selectByPrimaryKey(Integer idField);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByExampleSelective(AbiFormsForm record, AbiFormsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByExample(AbiFormsForm record, AbiFormsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByPrimaryKeySelective(AbiFormsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByPrimaryKey(AbiFormsForm record);
}