package it.studiofontanelli.jabistudio.spring.dao;

import it.studiofontanelli.jabistudio.spring.entity.AbiFormsDescr;
import it.studiofontanelli.jabistudio.spring.entity.AbiFormsDescrExample;
import java.util.List;

public interface AbiFormsDescrDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int countByExample(AbiFormsDescrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int deleteByExample(AbiFormsDescrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int deleteByPrimaryKey(Integer idForm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    void insert(AbiFormsDescr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    void insertSelective(AbiFormsDescr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    List selectByExample(AbiFormsDescrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    AbiFormsDescr selectByPrimaryKey(Integer idForm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByExampleSelective(AbiFormsDescr record, AbiFormsDescrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByExample(AbiFormsDescr record, AbiFormsDescrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByPrimaryKeySelective(AbiFormsDescr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    int updateByPrimaryKey(AbiFormsDescr record);
}