package it.studiofontanelli.jabistudio.spring.dao;

import it.studiofontanelli.jabistudio.spring.entity.AbiMainPofR;
import it.studiofontanelli.jabistudio.spring.entity.AbiMainPofRExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AbiMainPofRDAOImpl extends SqlMapClientDaoSupport implements AbiMainPofRDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public AbiMainPofRDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int countByExample(AbiMainPofRExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("_abi_main_pof_r.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int deleteByExample(AbiMainPofRExample example) {
        int rows = getSqlMapClientTemplate().delete("_abi_main_pof_r.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        AbiMainPofR _key = new AbiMainPofR();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("_abi_main_pof_r.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public void insert(AbiMainPofR record) {
        getSqlMapClientTemplate().insert("_abi_main_pof_r.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public void insertSelective(AbiMainPofR record) {
        getSqlMapClientTemplate().insert("_abi_main_pof_r.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public List selectByExample(AbiMainPofRExample example) {
        List list = getSqlMapClientTemplate().queryForList("_abi_main_pof_r.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public AbiMainPofR selectByPrimaryKey(Integer id) {
        AbiMainPofR _key = new AbiMainPofR();
        _key.setId(id);
        AbiMainPofR record = (AbiMainPofR) getSqlMapClientTemplate().queryForObject("_abi_main_pof_r.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int updateByExampleSelective(AbiMainPofR record, AbiMainPofRExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("_abi_main_pof_r.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int updateByExample(AbiMainPofR record, AbiMainPofRExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("_abi_main_pof_r.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int updateByPrimaryKeySelective(AbiMainPofR record) {
        int rows = getSqlMapClientTemplate().update("_abi_main_pof_r.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int updateByPrimaryKey(AbiMainPofR record) {
        int rows = getSqlMapClientTemplate().update("_abi_main_pof_r.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    protected static class UpdateByExampleParms extends AbiMainPofRExample {
        private Object record;

        public UpdateByExampleParms(Object record, AbiMainPofRExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}