package it.studiofontanelli.jabistudio.spring.dao;

import it.studiofontanelli.jabistudio.spring.entity.AbiMainPofT;
import it.studiofontanelli.jabistudio.spring.entity.AbiMainPofTExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AbiMainPofTDAOImpl extends SqlMapClientDaoSupport implements AbiMainPofTDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public AbiMainPofTDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int countByExample(AbiMainPofTExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("_abi_main_pof_t.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int deleteByExample(AbiMainPofTExample example) {
        int rows = getSqlMapClientTemplate().delete("_abi_main_pof_t.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        AbiMainPofT _key = new AbiMainPofT();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("_abi_main_pof_t.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public void insert(AbiMainPofT record) {
        getSqlMapClientTemplate().insert("_abi_main_pof_t.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public void insertSelective(AbiMainPofT record) {
        getSqlMapClientTemplate().insert("_abi_main_pof_t.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public List selectByExample(AbiMainPofTExample example) {
        List list = getSqlMapClientTemplate().queryForList("_abi_main_pof_t.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public AbiMainPofT selectByPrimaryKey(Integer id) {
        AbiMainPofT _key = new AbiMainPofT();
        _key.setId(id);
        AbiMainPofT record = (AbiMainPofT) getSqlMapClientTemplate().queryForObject("_abi_main_pof_t.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int updateByExampleSelective(AbiMainPofT record, AbiMainPofTExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("_abi_main_pof_t.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int updateByExample(AbiMainPofT record, AbiMainPofTExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("_abi_main_pof_t.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int updateByPrimaryKeySelective(AbiMainPofT record) {
        int rows = getSqlMapClientTemplate().update("_abi_main_pof_t.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public int updateByPrimaryKey(AbiMainPofT record) {
        int rows = getSqlMapClientTemplate().update("_abi_main_pof_t.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    protected static class UpdateByExampleParms extends AbiMainPofTExample {
        private Object record;

        public UpdateByExampleParms(Object record, AbiMainPofTExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}