package it.studiofontanelli.jabistudio.spring.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AbiFormsDescrExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    protected List oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public AbiFormsDescrExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    protected AbiFormsDescrExample(AbiFormsDescrExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.distinct = example.distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 15:19:10 CET 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdFormIsNull() {
            addCriterion("id_form is null");
            return (Criteria) this;
        }

        public Criteria andIdFormIsNotNull() {
            addCriterion("id_form is not null");
            return (Criteria) this;
        }

        public Criteria andIdFormEqualTo(Integer value) {
            addCriterion("id_form =", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormNotEqualTo(Integer value) {
            addCriterion("id_form <>", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormGreaterThan(Integer value) {
            addCriterion("id_form >", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_form >=", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormLessThan(Integer value) {
            addCriterion("id_form <", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormLessThanOrEqualTo(Integer value) {
            addCriterion("id_form <=", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormIn(List values) {
            addCriterion("id_form in", values, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormNotIn(List values) {
            addCriterion("id_form not in", values, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormBetween(Integer value1, Integer value2) {
            addCriterion("id_form between", value1, value2, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormNotBetween(Integer value1, Integer value2) {
            addCriterion("id_form not between", value1, value2, "idForm");
            return (Criteria) this;
        }

        public Criteria andRelnameIsNull() {
            addCriterion("relname is null");
            return (Criteria) this;
        }

        public Criteria andRelnameIsNotNull() {
            addCriterion("relname is not null");
            return (Criteria) this;
        }

        public Criteria andRelnameEqualTo(String value) {
            addCriterion("relname =", value, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameNotEqualTo(String value) {
            addCriterion("relname <>", value, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameGreaterThan(String value) {
            addCriterion("relname >", value, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameGreaterThanOrEqualTo(String value) {
            addCriterion("relname >=", value, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameLessThan(String value) {
            addCriterion("relname <", value, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameLessThanOrEqualTo(String value) {
            addCriterion("relname <=", value, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameLike(String value) {
            addCriterion("relname like", value, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameNotLike(String value) {
            addCriterion("relname not like", value, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameIn(List values) {
            addCriterion("relname in", values, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameNotIn(List values) {
            addCriterion("relname not in", values, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameBetween(String value1, String value2) {
            addCriterion("relname between", value1, value2, "relname");
            return (Criteria) this;
        }

        public Criteria andRelnameNotBetween(String value1, String value2) {
            addCriterion("relname not between", value1, value2, "relname");
            return (Criteria) this;
        }

        public Criteria andDescrIsNull() {
            addCriterion("descr is null");
            return (Criteria) this;
        }

        public Criteria andDescrIsNotNull() {
            addCriterion("descr is not null");
            return (Criteria) this;
        }

        public Criteria andDescrEqualTo(String value) {
            addCriterion("descr =", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotEqualTo(String value) {
            addCriterion("descr <>", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrGreaterThan(String value) {
            addCriterion("descr >", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrGreaterThanOrEqualTo(String value) {
            addCriterion("descr >=", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLessThan(String value) {
            addCriterion("descr <", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLessThanOrEqualTo(String value) {
            addCriterion("descr <=", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLike(String value) {
            addCriterion("descr like", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotLike(String value) {
            addCriterion("descr not like", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrIn(List values) {
            addCriterion("descr in", values, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotIn(List values) {
            addCriterion("descr not in", values, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrBetween(String value1, String value2) {
            addCriterion("descr between", value1, value2, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotBetween(String value1, String value2) {
            addCriterion("descr not between", value1, value2, "descr");
            return (Criteria) this;
        }

        public Criteria andSuccessIsNull() {
            addCriterion("success is null");
            return (Criteria) this;
        }

        public Criteria andSuccessIsNotNull() {
            addCriterion("success is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessEqualTo(String value) {
            addCriterion("success =", value, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessNotEqualTo(String value) {
            addCriterion("success <>", value, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessGreaterThan(String value) {
            addCriterion("success >", value, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessGreaterThanOrEqualTo(String value) {
            addCriterion("success >=", value, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessLessThan(String value) {
            addCriterion("success <", value, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessLessThanOrEqualTo(String value) {
            addCriterion("success <=", value, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessLike(String value) {
            addCriterion("success like", value, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessNotLike(String value) {
            addCriterion("success not like", value, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessIn(List values) {
            addCriterion("success in", values, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessNotIn(List values) {
            addCriterion("success not in", values, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessBetween(String value1, String value2) {
            addCriterion("success between", value1, value2, "success");
            return (Criteria) this;
        }

        public Criteria andSuccessNotBetween(String value1, String value2) {
            addCriterion("success not between", value1, value2, "success");
            return (Criteria) this;
        }

        public Criteria andDescr1IsNull() {
            addCriterion("descr1 is null");
            return (Criteria) this;
        }

        public Criteria andDescr1IsNotNull() {
            addCriterion("descr1 is not null");
            return (Criteria) this;
        }

        public Criteria andDescr1EqualTo(String value) {
            addCriterion("descr1 =", value, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1NotEqualTo(String value) {
            addCriterion("descr1 <>", value, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1GreaterThan(String value) {
            addCriterion("descr1 >", value, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1GreaterThanOrEqualTo(String value) {
            addCriterion("descr1 >=", value, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1LessThan(String value) {
            addCriterion("descr1 <", value, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1LessThanOrEqualTo(String value) {
            addCriterion("descr1 <=", value, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1Like(String value) {
            addCriterion("descr1 like", value, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1NotLike(String value) {
            addCriterion("descr1 not like", value, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1In(List values) {
            addCriterion("descr1 in", values, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1NotIn(List values) {
            addCriterion("descr1 not in", values, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1Between(String value1, String value2) {
            addCriterion("descr1 between", value1, value2, "descr1");
            return (Criteria) this;
        }

        public Criteria andDescr1NotBetween(String value1, String value2) {
            addCriterion("descr1 not between", value1, value2, "descr1");
            return (Criteria) this;
        }

        public Criteria andHandleIsNull() {
            addCriterion("handle is null");
            return (Criteria) this;
        }

        public Criteria andHandleIsNotNull() {
            addCriterion("handle is not null");
            return (Criteria) this;
        }

        public Criteria andHandleEqualTo(String value) {
            addCriterion("handle =", value, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleNotEqualTo(String value) {
            addCriterion("handle <>", value, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleGreaterThan(String value) {
            addCriterion("handle >", value, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleGreaterThanOrEqualTo(String value) {
            addCriterion("handle >=", value, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleLessThan(String value) {
            addCriterion("handle <", value, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleLessThanOrEqualTo(String value) {
            addCriterion("handle <=", value, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleLike(String value) {
            addCriterion("handle like", value, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleNotLike(String value) {
            addCriterion("handle not like", value, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleIn(List values) {
            addCriterion("handle in", values, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleNotIn(List values) {
            addCriterion("handle not in", values, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleBetween(String value1, String value2) {
            addCriterion("handle between", value1, value2, "handle");
            return (Criteria) this;
        }

        public Criteria andHandleNotBetween(String value1, String value2) {
            addCriterion("handle not between", value1, value2, "handle");
            return (Criteria) this;
        }

        public Criteria andDetailDescrIsNull() {
            addCriterion("detail_descr is null");
            return (Criteria) this;
        }

        public Criteria andDetailDescrIsNotNull() {
            addCriterion("detail_descr is not null");
            return (Criteria) this;
        }

        public Criteria andDetailDescrEqualTo(String value) {
            addCriterion("detail_descr =", value, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrNotEqualTo(String value) {
            addCriterion("detail_descr <>", value, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrGreaterThan(String value) {
            addCriterion("detail_descr >", value, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrGreaterThanOrEqualTo(String value) {
            addCriterion("detail_descr >=", value, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrLessThan(String value) {
            addCriterion("detail_descr <", value, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrLessThanOrEqualTo(String value) {
            addCriterion("detail_descr <=", value, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrLike(String value) {
            addCriterion("detail_descr like", value, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrNotLike(String value) {
            addCriterion("detail_descr not like", value, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrIn(List values) {
            addCriterion("detail_descr in", values, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrNotIn(List values) {
            addCriterion("detail_descr not in", values, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrBetween(String value1, String value2) {
            addCriterion("detail_descr between", value1, value2, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andDetailDescrNotBetween(String value1, String value2) {
            addCriterion("detail_descr not between", value1, value2, "detailDescr");
            return (Criteria) this;
        }

        public Criteria andOrderbyIsNull() {
            addCriterion("orderby is null");
            return (Criteria) this;
        }

        public Criteria andOrderbyIsNotNull() {
            addCriterion("orderby is not null");
            return (Criteria) this;
        }

        public Criteria andOrderbyEqualTo(String value) {
            addCriterion("orderby =", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyNotEqualTo(String value) {
            addCriterion("orderby <>", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyGreaterThan(String value) {
            addCriterion("orderby >", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyGreaterThanOrEqualTo(String value) {
            addCriterion("orderby >=", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyLessThan(String value) {
            addCriterion("orderby <", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyLessThanOrEqualTo(String value) {
            addCriterion("orderby <=", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyLike(String value) {
            addCriterion("orderby like", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyNotLike(String value) {
            addCriterion("orderby not like", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyIn(List values) {
            addCriterion("orderby in", values, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyNotIn(List values) {
            addCriterion("orderby not in", values, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyBetween(String value1, String value2) {
            addCriterion("orderby between", value1, value2, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyNotBetween(String value1, String value2) {
            addCriterion("orderby not between", value1, value2, "orderby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 07 15:19:10 CET 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}