package it.studiofontanelli.jabistudio.mybatis.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AbiFormsFormExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    protected List oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public AbiFormsFormExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    protected AbiFormsFormExample(AbiFormsFormExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.distinct = example.distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdFieldIsNull() {
            addCriterion("id_field is null");
            return (Criteria) this;
        }

        public Criteria andIdFieldIsNotNull() {
            addCriterion("id_field is not null");
            return (Criteria) this;
        }

        public Criteria andIdFieldEqualTo(Integer value) {
            addCriterion("id_field =", value, "idField");
            return (Criteria) this;
        }

        public Criteria andIdFieldNotEqualTo(Integer value) {
            addCriterion("id_field <>", value, "idField");
            return (Criteria) this;
        }

        public Criteria andIdFieldGreaterThan(Integer value) {
            addCriterion("id_field >", value, "idField");
            return (Criteria) this;
        }

        public Criteria andIdFieldGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_field >=", value, "idField");
            return (Criteria) this;
        }

        public Criteria andIdFieldLessThan(Integer value) {
            addCriterion("id_field <", value, "idField");
            return (Criteria) this;
        }

        public Criteria andIdFieldLessThanOrEqualTo(Integer value) {
            addCriterion("id_field <=", value, "idField");
            return (Criteria) this;
        }

        public Criteria andIdFieldIn(List values) {
            addCriterion("id_field in", values, "idField");
            return (Criteria) this;
        }

        public Criteria andIdFieldNotIn(List values) {
            addCriterion("id_field not in", values, "idField");
            return (Criteria) this;
        }

        public Criteria andIdFieldBetween(Integer value1, Integer value2) {
            addCriterion("id_field between", value1, value2, "idField");
            return (Criteria) this;
        }

        public Criteria andIdFieldNotBetween(Integer value1, Integer value2) {
            addCriterion("id_field not between", value1, value2, "idField");
            return (Criteria) this;
        }

        public Criteria andIdFormIsNull() {
            addCriterion("id_form is null");
            return (Criteria) this;
        }

        public Criteria andIdFormIsNotNull() {
            addCriterion("id_form is not null");
            return (Criteria) this;
        }

        public Criteria andIdFormEqualTo(Integer value) {
            addCriterion("id_form =", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormNotEqualTo(Integer value) {
            addCriterion("id_form <>", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormGreaterThan(Integer value) {
            addCriterion("id_form >", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_form >=", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormLessThan(Integer value) {
            addCriterion("id_form <", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormLessThanOrEqualTo(Integer value) {
            addCriterion("id_form <=", value, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormIn(List values) {
            addCriterion("id_form in", values, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormNotIn(List values) {
            addCriterion("id_form not in", values, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormBetween(Integer value1, Integer value2) {
            addCriterion("id_form between", value1, value2, "idForm");
            return (Criteria) this;
        }

        public Criteria andIdFormNotBetween(Integer value1, Integer value2) {
            addCriterion("id_form not between", value1, value2, "idForm");
            return (Criteria) this;
        }

        public Criteria andFieldNameIsNull() {
            addCriterion("field_name is null");
            return (Criteria) this;
        }

        public Criteria andFieldNameIsNotNull() {
            addCriterion("field_name is not null");
            return (Criteria) this;
        }

        public Criteria andFieldNameEqualTo(String value) {
            addCriterion("field_name =", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotEqualTo(String value) {
            addCriterion("field_name <>", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameGreaterThan(String value) {
            addCriterion("field_name >", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameGreaterThanOrEqualTo(String value) {
            addCriterion("field_name >=", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameLessThan(String value) {
            addCriterion("field_name <", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameLessThanOrEqualTo(String value) {
            addCriterion("field_name <=", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameLike(String value) {
            addCriterion("field_name like", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotLike(String value) {
            addCriterion("field_name not like", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameIn(List values) {
            addCriterion("field_name in", values, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotIn(List values) {
            addCriterion("field_name not in", values, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameBetween(String value1, String value2) {
            addCriterion("field_name between", value1, value2, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotBetween(String value1, String value2) {
            addCriterion("field_name not between", value1, value2, "fieldName");
            return (Criteria) this;
        }

        public Criteria andObjectNameIsNull() {
            addCriterion("object_name is null");
            return (Criteria) this;
        }

        public Criteria andObjectNameIsNotNull() {
            addCriterion("object_name is not null");
            return (Criteria) this;
        }

        public Criteria andObjectNameEqualTo(String value) {
            addCriterion("object_name =", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameNotEqualTo(String value) {
            addCriterion("object_name <>", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameGreaterThan(String value) {
            addCriterion("object_name >", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("object_name >=", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameLessThan(String value) {
            addCriterion("object_name <", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameLessThanOrEqualTo(String value) {
            addCriterion("object_name <=", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameLike(String value) {
            addCriterion("object_name like", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameNotLike(String value) {
            addCriterion("object_name not like", value, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameIn(List values) {
            addCriterion("object_name in", values, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameNotIn(List values) {
            addCriterion("object_name not in", values, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameBetween(String value1, String value2) {
            addCriterion("object_name between", value1, value2, "objectName");
            return (Criteria) this;
        }

        public Criteria andObjectNameNotBetween(String value1, String value2) {
            addCriterion("object_name not between", value1, value2, "objectName");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameIsNull() {
            addCriterion("url_id_object_name is null");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameIsNotNull() {
            addCriterion("url_id_object_name is not null");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameEqualTo(String value) {
            addCriterion("url_id_object_name =", value, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameNotEqualTo(String value) {
            addCriterion("url_id_object_name <>", value, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameGreaterThan(String value) {
            addCriterion("url_id_object_name >", value, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("url_id_object_name >=", value, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameLessThan(String value) {
            addCriterion("url_id_object_name <", value, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameLessThanOrEqualTo(String value) {
            addCriterion("url_id_object_name <=", value, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameLike(String value) {
            addCriterion("url_id_object_name like", value, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameNotLike(String value) {
            addCriterion("url_id_object_name not like", value, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameIn(List values) {
            addCriterion("url_id_object_name in", values, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameNotIn(List values) {
            addCriterion("url_id_object_name not in", values, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameBetween(String value1, String value2) {
            addCriterion("url_id_object_name between", value1, value2, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andUrlIdObjectNameNotBetween(String value1, String value2) {
            addCriterion("url_id_object_name not between", value1, value2, "urlIdObjectName");
            return (Criteria) this;
        }

        public Criteria andPosIsNull() {
            addCriterion("pos is null");
            return (Criteria) this;
        }

        public Criteria andPosIsNotNull() {
            addCriterion("pos is not null");
            return (Criteria) this;
        }

        public Criteria andPosEqualTo(Short value) {
            addCriterion("pos =", value, "pos");
            return (Criteria) this;
        }

        public Criteria andPosNotEqualTo(Short value) {
            addCriterion("pos <>", value, "pos");
            return (Criteria) this;
        }

        public Criteria andPosGreaterThan(Short value) {
            addCriterion("pos >", value, "pos");
            return (Criteria) this;
        }

        public Criteria andPosGreaterThanOrEqualTo(Short value) {
            addCriterion("pos >=", value, "pos");
            return (Criteria) this;
        }

        public Criteria andPosLessThan(Short value) {
            addCriterion("pos <", value, "pos");
            return (Criteria) this;
        }

        public Criteria andPosLessThanOrEqualTo(Short value) {
            addCriterion("pos <=", value, "pos");
            return (Criteria) this;
        }

        public Criteria andPosIn(List values) {
            addCriterion("pos in", values, "pos");
            return (Criteria) this;
        }

        public Criteria andPosNotIn(List values) {
            addCriterion("pos not in", values, "pos");
            return (Criteria) this;
        }

        public Criteria andPosBetween(Short value1, Short value2) {
            addCriterion("pos between", value1, value2, "pos");
            return (Criteria) this;
        }

        public Criteria andPosNotBetween(Short value1, Short value2) {
            addCriterion("pos not between", value1, value2, "pos");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameIsNull() {
            addCriterion("sel_lk_relname is null");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameIsNotNull() {
            addCriterion("sel_lk_relname is not null");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameEqualTo(String value) {
            addCriterion("sel_lk_relname =", value, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameNotEqualTo(String value) {
            addCriterion("sel_lk_relname <>", value, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameGreaterThan(String value) {
            addCriterion("sel_lk_relname >", value, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameGreaterThanOrEqualTo(String value) {
            addCriterion("sel_lk_relname >=", value, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameLessThan(String value) {
            addCriterion("sel_lk_relname <", value, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameLessThanOrEqualTo(String value) {
            addCriterion("sel_lk_relname <=", value, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameLike(String value) {
            addCriterion("sel_lk_relname like", value, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameNotLike(String value) {
            addCriterion("sel_lk_relname not like", value, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameIn(List values) {
            addCriterion("sel_lk_relname in", values, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameNotIn(List values) {
            addCriterion("sel_lk_relname not in", values, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameBetween(String value1, String value2) {
            addCriterion("sel_lk_relname between", value1, value2, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andSelLkRelnameNotBetween(String value1, String value2) {
            addCriterion("sel_lk_relname not between", value1, value2, "selLkRelname");
            return (Criteria) this;
        }

        public Criteria andFixedValueIsNull() {
            addCriterion("fixed_value is null");
            return (Criteria) this;
        }

        public Criteria andFixedValueIsNotNull() {
            addCriterion("fixed_value is not null");
            return (Criteria) this;
        }

        public Criteria andFixedValueEqualTo(String value) {
            addCriterion("fixed_value =", value, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueNotEqualTo(String value) {
            addCriterion("fixed_value <>", value, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueGreaterThan(String value) {
            addCriterion("fixed_value >", value, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueGreaterThanOrEqualTo(String value) {
            addCriterion("fixed_value >=", value, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueLessThan(String value) {
            addCriterion("fixed_value <", value, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueLessThanOrEqualTo(String value) {
            addCriterion("fixed_value <=", value, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueLike(String value) {
            addCriterion("fixed_value like", value, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueNotLike(String value) {
            addCriterion("fixed_value not like", value, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueIn(List values) {
            addCriterion("fixed_value in", values, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueNotIn(List values) {
            addCriterion("fixed_value not in", values, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueBetween(String value1, String value2) {
            addCriterion("fixed_value between", value1, value2, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFixedValueNotBetween(String value1, String value2) {
            addCriterion("fixed_value not between", value1, value2, "fixedValue");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorIsNull() {
            addCriterion("field_decorator is null");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorIsNotNull() {
            addCriterion("field_decorator is not null");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorEqualTo(String value) {
            addCriterion("field_decorator =", value, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorNotEqualTo(String value) {
            addCriterion("field_decorator <>", value, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorGreaterThan(String value) {
            addCriterion("field_decorator >", value, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorGreaterThanOrEqualTo(String value) {
            addCriterion("field_decorator >=", value, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorLessThan(String value) {
            addCriterion("field_decorator <", value, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorLessThanOrEqualTo(String value) {
            addCriterion("field_decorator <=", value, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorLike(String value) {
            addCriterion("field_decorator like", value, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorNotLike(String value) {
            addCriterion("field_decorator not like", value, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorIn(List values) {
            addCriterion("field_decorator in", values, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorNotIn(List values) {
            addCriterion("field_decorator not in", values, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorBetween(String value1, String value2) {
            addCriterion("field_decorator between", value1, value2, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andFieldDecoratorNotBetween(String value1, String value2) {
            addCriterion("field_decorator not between", value1, value2, "fieldDecorator");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeIsNull() {
            addCriterion("id_field_type is null");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeIsNotNull() {
            addCriterion("id_field_type is not null");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeEqualTo(String value) {
            addCriterion("id_field_type =", value, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeNotEqualTo(String value) {
            addCriterion("id_field_type <>", value, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeGreaterThan(String value) {
            addCriterion("id_field_type >", value, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeGreaterThanOrEqualTo(String value) {
            addCriterion("id_field_type >=", value, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeLessThan(String value) {
            addCriterion("id_field_type <", value, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeLessThanOrEqualTo(String value) {
            addCriterion("id_field_type <=", value, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeLike(String value) {
            addCriterion("id_field_type like", value, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeNotLike(String value) {
            addCriterion("id_field_type not like", value, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeIn(List values) {
            addCriterion("id_field_type in", values, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeNotIn(List values) {
            addCriterion("id_field_type not in", values, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeBetween(String value1, String value2) {
            addCriterion("id_field_type between", value1, value2, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andIdFieldTypeNotBetween(String value1, String value2) {
            addCriterion("id_field_type not between", value1, value2, "idFieldType");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityIsNull() {
            addCriterion("detail_visibility is null");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityIsNotNull() {
            addCriterion("detail_visibility is not null");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityEqualTo(Boolean value) {
            addCriterion("detail_visibility =", value, "detailVisibility");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityNotEqualTo(Boolean value) {
            addCriterion("detail_visibility <>", value, "detailVisibility");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityGreaterThan(Boolean value) {
            addCriterion("detail_visibility >", value, "detailVisibility");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityGreaterThanOrEqualTo(Boolean value) {
            addCriterion("detail_visibility >=", value, "detailVisibility");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityLessThan(Boolean value) {
            addCriterion("detail_visibility <", value, "detailVisibility");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityLessThanOrEqualTo(Boolean value) {
            addCriterion("detail_visibility <=", value, "detailVisibility");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityIn(List values) {
            addCriterion("detail_visibility in", values, "detailVisibility");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityNotIn(List values) {
            addCriterion("detail_visibility not in", values, "detailVisibility");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityBetween(Boolean value1, Boolean value2) {
            addCriterion("detail_visibility between", value1, value2, "detailVisibility");
            return (Criteria) this;
        }

        public Criteria andDetailVisibilityNotBetween(Boolean value1, Boolean value2) {
            addCriterion("detail_visibility not between", value1, value2, "detailVisibility");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _abi_forms_form
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 07 14:58:43 CET 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}