package it.studiofontanelli.jabistudio.mybatis.entity;

public class AbiFormsDescr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_descr.id_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Integer idForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_descr.relname
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String relname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_descr.descr
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_descr.success
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_descr.descr1
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String descr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_descr.handle
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String handle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_descr.detail_descr
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String detailDescr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_descr.orderby
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String orderby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_descr.id_form
     *
     * @return the value of _abi_forms_descr.id_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Integer getIdForm() {
        return idForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_descr.id_form
     *
     * @param idForm the value for _abi_forms_descr.id_form
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setIdForm(Integer idForm) {
        this.idForm = idForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_descr.relname
     *
     * @return the value of _abi_forms_descr.relname
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getRelname() {
        return relname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_descr.relname
     *
     * @param relname the value for _abi_forms_descr.relname
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setRelname(String relname) {
        this.relname = relname == null ? null : relname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_descr.descr
     *
     * @return the value of _abi_forms_descr.descr
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_descr.descr
     *
     * @param descr the value for _abi_forms_descr.descr
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_descr.success
     *
     * @return the value of _abi_forms_descr.success
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_descr.success
     *
     * @param success the value for _abi_forms_descr.success
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setSuccess(String success) {
        this.success = success == null ? null : success.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_descr.descr1
     *
     * @return the value of _abi_forms_descr.descr1
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getDescr1() {
        return descr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_descr.descr1
     *
     * @param descr1 the value for _abi_forms_descr.descr1
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setDescr1(String descr1) {
        this.descr1 = descr1 == null ? null : descr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_descr.handle
     *
     * @return the value of _abi_forms_descr.handle
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getHandle() {
        return handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_descr.handle
     *
     * @param handle the value for _abi_forms_descr.handle
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setHandle(String handle) {
        this.handle = handle == null ? null : handle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_descr.detail_descr
     *
     * @return the value of _abi_forms_descr.detail_descr
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getDetailDescr() {
        return detailDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_descr.detail_descr
     *
     * @param detailDescr the value for _abi_forms_descr.detail_descr
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setDetailDescr(String detailDescr) {
        this.detailDescr = detailDescr == null ? null : detailDescr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_descr.orderby
     *
     * @return the value of _abi_forms_descr.orderby
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_descr.orderby
     *
     * @param orderby the value for _abi_forms_descr.orderby
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setOrderby(String orderby) {
        this.orderby = orderby == null ? null : orderby.trim();
    }
}