package it.studiofontanelli.jabistudio.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

public class AbiMainPofT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.id
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.sourceid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String sourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.statusid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String statusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.userid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.contactid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Integer contactid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.note
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.insert_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Date insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.update_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.poft_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Date poftDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.paytypeid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String paytypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.invoiceid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Integer invoiceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.invoice_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Date invoiceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.discount
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Double discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.ship_fee
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private BigDecimal shipFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.refid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Integer refid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.discount_per
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Short discountPer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.typeid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private String typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.bankid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Short bankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.transid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Short transid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.transcauseid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Short transcauseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_t.itemaspectid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    private Short itemaspectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.id
     *
     * @return the value of _abi_main_pof_t.id
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.id
     *
     * @param id the value for _abi_main_pof_t.id
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.sourceid
     *
     * @return the value of _abi_main_pof_t.sourceid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.sourceid
     *
     * @param sourceid the value for _abi_main_pof_t.sourceid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setSourceid(String sourceid) {
        this.sourceid = sourceid == null ? null : sourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.statusid
     *
     * @return the value of _abi_main_pof_t.statusid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.statusid
     *
     * @param statusid the value for _abi_main_pof_t.statusid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setStatusid(String statusid) {
        this.statusid = statusid == null ? null : statusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.userid
     *
     * @return the value of _abi_main_pof_t.userid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.userid
     *
     * @param userid the value for _abi_main_pof_t.userid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.contactid
     *
     * @return the value of _abi_main_pof_t.contactid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Integer getContactid() {
        return contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.contactid
     *
     * @param contactid the value for _abi_main_pof_t.contactid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setContactid(Integer contactid) {
        this.contactid = contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.note
     *
     * @return the value of _abi_main_pof_t.note
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.note
     *
     * @param note the value for _abi_main_pof_t.note
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.insert_date
     *
     * @return the value of _abi_main_pof_t.insert_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.insert_date
     *
     * @param insertDate the value for _abi_main_pof_t.insert_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.update_date
     *
     * @return the value of _abi_main_pof_t.update_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.update_date
     *
     * @param updateDate the value for _abi_main_pof_t.update_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.poft_date
     *
     * @return the value of _abi_main_pof_t.poft_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Date getPoftDate() {
        return poftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.poft_date
     *
     * @param poftDate the value for _abi_main_pof_t.poft_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setPoftDate(Date poftDate) {
        this.poftDate = poftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.paytypeid
     *
     * @return the value of _abi_main_pof_t.paytypeid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getPaytypeid() {
        return paytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.paytypeid
     *
     * @param paytypeid the value for _abi_main_pof_t.paytypeid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setPaytypeid(String paytypeid) {
        this.paytypeid = paytypeid == null ? null : paytypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.invoiceid
     *
     * @return the value of _abi_main_pof_t.invoiceid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Integer getInvoiceid() {
        return invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.invoiceid
     *
     * @param invoiceid the value for _abi_main_pof_t.invoiceid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.invoice_date
     *
     * @return the value of _abi_main_pof_t.invoice_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Date getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.invoice_date
     *
     * @param invoiceDate the value for _abi_main_pof_t.invoice_date
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.discount
     *
     * @return the value of _abi_main_pof_t.discount
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.discount
     *
     * @param discount the value for _abi_main_pof_t.discount
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.ship_fee
     *
     * @return the value of _abi_main_pof_t.ship_fee
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public BigDecimal getShipFee() {
        return shipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.ship_fee
     *
     * @param shipFee the value for _abi_main_pof_t.ship_fee
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setShipFee(BigDecimal shipFee) {
        this.shipFee = shipFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.refid
     *
     * @return the value of _abi_main_pof_t.refid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Integer getRefid() {
        return refid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.refid
     *
     * @param refid the value for _abi_main_pof_t.refid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setRefid(Integer refid) {
        this.refid = refid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.discount_per
     *
     * @return the value of _abi_main_pof_t.discount_per
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Short getDiscountPer() {
        return discountPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.discount_per
     *
     * @param discountPer the value for _abi_main_pof_t.discount_per
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setDiscountPer(Short discountPer) {
        this.discountPer = discountPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.typeid
     *
     * @return the value of _abi_main_pof_t.typeid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.typeid
     *
     * @param typeid the value for _abi_main_pof_t.typeid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.bankid
     *
     * @return the value of _abi_main_pof_t.bankid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Short getBankid() {
        return bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.bankid
     *
     * @param bankid the value for _abi_main_pof_t.bankid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setBankid(Short bankid) {
        this.bankid = bankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.transid
     *
     * @return the value of _abi_main_pof_t.transid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Short getTransid() {
        return transid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.transid
     *
     * @param transid the value for _abi_main_pof_t.transid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setTransid(Short transid) {
        this.transid = transid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.transcauseid
     *
     * @return the value of _abi_main_pof_t.transcauseid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Short getTranscauseid() {
        return transcauseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.transcauseid
     *
     * @param transcauseid the value for _abi_main_pof_t.transcauseid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setTranscauseid(Short transcauseid) {
        this.transcauseid = transcauseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_t.itemaspectid
     *
     * @return the value of _abi_main_pof_t.itemaspectid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public Short getItemaspectid() {
        return itemaspectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_t.itemaspectid
     *
     * @param itemaspectid the value for _abi_main_pof_t.itemaspectid
     *
     * @mbggenerated Mon Mar 07 14:58:43 CET 2016
     */
    public void setItemaspectid(Short itemaspectid) {
        this.itemaspectid = itemaspectid;
    }
}