package it.studiofontanelli.jabistudio.entity;

public class AbiFormsForm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.id_field
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private Integer idField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.id_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private Integer idForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.field_name
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.object_name
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private String objectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.url
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.url_id_object_name
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private String urlIdObjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.pos
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private Short pos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.sel_lk_relname
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private String selLkRelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.fixed_value
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private String fixedValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.field_decorator
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private String fieldDecorator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.id_field_type
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private String idFieldType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_forms_form.detail_visibility
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    private Boolean detailVisibility;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.id_field
     *
     * @return the value of _abi_forms_form.id_field
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public Integer getIdField() {
        return idField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.id_field
     *
     * @param idField the value for _abi_forms_form.id_field
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setIdField(Integer idField) {
        this.idField = idField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.id_form
     *
     * @return the value of _abi_forms_form.id_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public Integer getIdForm() {
        return idForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.id_form
     *
     * @param idForm the value for _abi_forms_form.id_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setIdForm(Integer idForm) {
        this.idForm = idForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.field_name
     *
     * @return the value of _abi_forms_form.field_name
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.field_name
     *
     * @param fieldName the value for _abi_forms_form.field_name
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.object_name
     *
     * @return the value of _abi_forms_form.object_name
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.object_name
     *
     * @param objectName the value for _abi_forms_form.object_name
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName == null ? null : objectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.url
     *
     * @return the value of _abi_forms_form.url
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.url
     *
     * @param url the value for _abi_forms_form.url
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.url_id_object_name
     *
     * @return the value of _abi_forms_form.url_id_object_name
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public String getUrlIdObjectName() {
        return urlIdObjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.url_id_object_name
     *
     * @param urlIdObjectName the value for _abi_forms_form.url_id_object_name
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setUrlIdObjectName(String urlIdObjectName) {
        this.urlIdObjectName = urlIdObjectName == null ? null : urlIdObjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.pos
     *
     * @return the value of _abi_forms_form.pos
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public Short getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.pos
     *
     * @param pos the value for _abi_forms_form.pos
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setPos(Short pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.sel_lk_relname
     *
     * @return the value of _abi_forms_form.sel_lk_relname
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public String getSelLkRelname() {
        return selLkRelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.sel_lk_relname
     *
     * @param selLkRelname the value for _abi_forms_form.sel_lk_relname
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setSelLkRelname(String selLkRelname) {
        this.selLkRelname = selLkRelname == null ? null : selLkRelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.fixed_value
     *
     * @return the value of _abi_forms_form.fixed_value
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public String getFixedValue() {
        return fixedValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.fixed_value
     *
     * @param fixedValue the value for _abi_forms_form.fixed_value
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setFixedValue(String fixedValue) {
        this.fixedValue = fixedValue == null ? null : fixedValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.field_decorator
     *
     * @return the value of _abi_forms_form.field_decorator
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public String getFieldDecorator() {
        return fieldDecorator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.field_decorator
     *
     * @param fieldDecorator the value for _abi_forms_form.field_decorator
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setFieldDecorator(String fieldDecorator) {
        this.fieldDecorator = fieldDecorator == null ? null : fieldDecorator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.id_field_type
     *
     * @return the value of _abi_forms_form.id_field_type
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public String getIdFieldType() {
        return idFieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.id_field_type
     *
     * @param idFieldType the value for _abi_forms_form.id_field_type
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setIdFieldType(String idFieldType) {
        this.idFieldType = idFieldType == null ? null : idFieldType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_forms_form.detail_visibility
     *
     * @return the value of _abi_forms_form.detail_visibility
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public Boolean getDetailVisibility() {
        return detailVisibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_forms_form.detail_visibility
     *
     * @param detailVisibility the value for _abi_forms_form.detail_visibility
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setDetailVisibility(Boolean detailVisibility) {
        this.detailVisibility = detailVisibility;
    }
}