package it.studiofontanelli.jabistudio.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AbiMainPofTExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public AbiMainPofTExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSourceidIsNull() {
            addCriterion("sourceid is null");
            return (Criteria) this;
        }

        public Criteria andSourceidIsNotNull() {
            addCriterion("sourceid is not null");
            return (Criteria) this;
        }

        public Criteria andSourceidEqualTo(String value) {
            addCriterion("sourceid =", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotEqualTo(String value) {
            addCriterion("sourceid <>", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidGreaterThan(String value) {
            addCriterion("sourceid >", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidGreaterThanOrEqualTo(String value) {
            addCriterion("sourceid >=", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidLessThan(String value) {
            addCriterion("sourceid <", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidLessThanOrEqualTo(String value) {
            addCriterion("sourceid <=", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidLike(String value) {
            addCriterion("sourceid like", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotLike(String value) {
            addCriterion("sourceid not like", value, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidIn(List<String> values) {
            addCriterion("sourceid in", values, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotIn(List<String> values) {
            addCriterion("sourceid not in", values, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidBetween(String value1, String value2) {
            addCriterion("sourceid between", value1, value2, "sourceid");
            return (Criteria) this;
        }

        public Criteria andSourceidNotBetween(String value1, String value2) {
            addCriterion("sourceid not between", value1, value2, "sourceid");
            return (Criteria) this;
        }

        public Criteria andStatusidIsNull() {
            addCriterion("statusid is null");
            return (Criteria) this;
        }

        public Criteria andStatusidIsNotNull() {
            addCriterion("statusid is not null");
            return (Criteria) this;
        }

        public Criteria andStatusidEqualTo(String value) {
            addCriterion("statusid =", value, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidNotEqualTo(String value) {
            addCriterion("statusid <>", value, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidGreaterThan(String value) {
            addCriterion("statusid >", value, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidGreaterThanOrEqualTo(String value) {
            addCriterion("statusid >=", value, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidLessThan(String value) {
            addCriterion("statusid <", value, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidLessThanOrEqualTo(String value) {
            addCriterion("statusid <=", value, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidLike(String value) {
            addCriterion("statusid like", value, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidNotLike(String value) {
            addCriterion("statusid not like", value, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidIn(List<String> values) {
            addCriterion("statusid in", values, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidNotIn(List<String> values) {
            addCriterion("statusid not in", values, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidBetween(String value1, String value2) {
            addCriterion("statusid between", value1, value2, "statusid");
            return (Criteria) this;
        }

        public Criteria andStatusidNotBetween(String value1, String value2) {
            addCriterion("statusid not between", value1, value2, "statusid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andContactidIsNull() {
            addCriterion("contactid is null");
            return (Criteria) this;
        }

        public Criteria andContactidIsNotNull() {
            addCriterion("contactid is not null");
            return (Criteria) this;
        }

        public Criteria andContactidEqualTo(Integer value) {
            addCriterion("contactid =", value, "contactid");
            return (Criteria) this;
        }

        public Criteria andContactidNotEqualTo(Integer value) {
            addCriterion("contactid <>", value, "contactid");
            return (Criteria) this;
        }

        public Criteria andContactidGreaterThan(Integer value) {
            addCriterion("contactid >", value, "contactid");
            return (Criteria) this;
        }

        public Criteria andContactidGreaterThanOrEqualTo(Integer value) {
            addCriterion("contactid >=", value, "contactid");
            return (Criteria) this;
        }

        public Criteria andContactidLessThan(Integer value) {
            addCriterion("contactid <", value, "contactid");
            return (Criteria) this;
        }

        public Criteria andContactidLessThanOrEqualTo(Integer value) {
            addCriterion("contactid <=", value, "contactid");
            return (Criteria) this;
        }

        public Criteria andContactidIn(List<Integer> values) {
            addCriterion("contactid in", values, "contactid");
            return (Criteria) this;
        }

        public Criteria andContactidNotIn(List<Integer> values) {
            addCriterion("contactid not in", values, "contactid");
            return (Criteria) this;
        }

        public Criteria andContactidBetween(Integer value1, Integer value2) {
            addCriterion("contactid between", value1, value2, "contactid");
            return (Criteria) this;
        }

        public Criteria andContactidNotBetween(Integer value1, Integer value2) {
            addCriterion("contactid not between", value1, value2, "contactid");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andInsertDateIsNull() {
            addCriterion("insert_date is null");
            return (Criteria) this;
        }

        public Criteria andInsertDateIsNotNull() {
            addCriterion("insert_date is not null");
            return (Criteria) this;
        }

        public Criteria andInsertDateEqualTo(Date value) {
            addCriterion("insert_date =", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotEqualTo(Date value) {
            addCriterion("insert_date <>", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateGreaterThan(Date value) {
            addCriterion("insert_date >", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateGreaterThanOrEqualTo(Date value) {
            addCriterion("insert_date >=", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateLessThan(Date value) {
            addCriterion("insert_date <", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateLessThanOrEqualTo(Date value) {
            addCriterion("insert_date <=", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateIn(List<Date> values) {
            addCriterion("insert_date in", values, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotIn(List<Date> values) {
            addCriterion("insert_date not in", values, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateBetween(Date value1, Date value2) {
            addCriterion("insert_date between", value1, value2, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotBetween(Date value1, Date value2) {
            addCriterion("insert_date not between", value1, value2, "insertDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterionForJDBCDate("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterionForJDBCDate("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterionForJDBCDate("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andPoftDateIsNull() {
            addCriterion("poft_date is null");
            return (Criteria) this;
        }

        public Criteria andPoftDateIsNotNull() {
            addCriterion("poft_date is not null");
            return (Criteria) this;
        }

        public Criteria andPoftDateEqualTo(Date value) {
            addCriterionForJDBCDate("poft_date =", value, "poftDate");
            return (Criteria) this;
        }

        public Criteria andPoftDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("poft_date <>", value, "poftDate");
            return (Criteria) this;
        }

        public Criteria andPoftDateGreaterThan(Date value) {
            addCriterionForJDBCDate("poft_date >", value, "poftDate");
            return (Criteria) this;
        }

        public Criteria andPoftDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("poft_date >=", value, "poftDate");
            return (Criteria) this;
        }

        public Criteria andPoftDateLessThan(Date value) {
            addCriterionForJDBCDate("poft_date <", value, "poftDate");
            return (Criteria) this;
        }

        public Criteria andPoftDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("poft_date <=", value, "poftDate");
            return (Criteria) this;
        }

        public Criteria andPoftDateIn(List<Date> values) {
            addCriterionForJDBCDate("poft_date in", values, "poftDate");
            return (Criteria) this;
        }

        public Criteria andPoftDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("poft_date not in", values, "poftDate");
            return (Criteria) this;
        }

        public Criteria andPoftDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("poft_date between", value1, value2, "poftDate");
            return (Criteria) this;
        }

        public Criteria andPoftDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("poft_date not between", value1, value2, "poftDate");
            return (Criteria) this;
        }

        public Criteria andPaytypeidIsNull() {
            addCriterion("paytypeid is null");
            return (Criteria) this;
        }

        public Criteria andPaytypeidIsNotNull() {
            addCriterion("paytypeid is not null");
            return (Criteria) this;
        }

        public Criteria andPaytypeidEqualTo(String value) {
            addCriterion("paytypeid =", value, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidNotEqualTo(String value) {
            addCriterion("paytypeid <>", value, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidGreaterThan(String value) {
            addCriterion("paytypeid >", value, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidGreaterThanOrEqualTo(String value) {
            addCriterion("paytypeid >=", value, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidLessThan(String value) {
            addCriterion("paytypeid <", value, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidLessThanOrEqualTo(String value) {
            addCriterion("paytypeid <=", value, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidLike(String value) {
            addCriterion("paytypeid like", value, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidNotLike(String value) {
            addCriterion("paytypeid not like", value, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidIn(List<String> values) {
            addCriterion("paytypeid in", values, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidNotIn(List<String> values) {
            addCriterion("paytypeid not in", values, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidBetween(String value1, String value2) {
            addCriterion("paytypeid between", value1, value2, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andPaytypeidNotBetween(String value1, String value2) {
            addCriterion("paytypeid not between", value1, value2, "paytypeid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidIsNull() {
            addCriterion("invoiceid is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceidIsNotNull() {
            addCriterion("invoiceid is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceidEqualTo(Integer value) {
            addCriterion("invoiceid =", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidNotEqualTo(Integer value) {
            addCriterion("invoiceid <>", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidGreaterThan(Integer value) {
            addCriterion("invoiceid >", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("invoiceid >=", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidLessThan(Integer value) {
            addCriterion("invoiceid <", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidLessThanOrEqualTo(Integer value) {
            addCriterion("invoiceid <=", value, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidIn(List<Integer> values) {
            addCriterion("invoiceid in", values, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidNotIn(List<Integer> values) {
            addCriterion("invoiceid not in", values, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidBetween(Integer value1, Integer value2) {
            addCriterion("invoiceid between", value1, value2, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceidNotBetween(Integer value1, Integer value2) {
            addCriterion("invoiceid not between", value1, value2, "invoiceid");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateIsNull() {
            addCriterion("invoice_date is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateIsNotNull() {
            addCriterion("invoice_date is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateEqualTo(Date value) {
            addCriterionForJDBCDate("invoice_date =", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("invoice_date <>", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateGreaterThan(Date value) {
            addCriterionForJDBCDate("invoice_date >", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("invoice_date >=", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateLessThan(Date value) {
            addCriterionForJDBCDate("invoice_date <", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("invoice_date <=", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateIn(List<Date> values) {
            addCriterionForJDBCDate("invoice_date in", values, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("invoice_date not in", values, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("invoice_date between", value1, value2, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("invoice_date not between", value1, value2, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNull() {
            addCriterion("discount is null");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNotNull() {
            addCriterion("discount is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountEqualTo(Double value) {
            addCriterion("discount =", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotEqualTo(Double value) {
            addCriterion("discount <>", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThan(Double value) {
            addCriterion("discount >", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThanOrEqualTo(Double value) {
            addCriterion("discount >=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThan(Double value) {
            addCriterion("discount <", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThanOrEqualTo(Double value) {
            addCriterion("discount <=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountIn(List<Double> values) {
            addCriterion("discount in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotIn(List<Double> values) {
            addCriterion("discount not in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountBetween(Double value1, Double value2) {
            addCriterion("discount between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotBetween(Double value1, Double value2) {
            addCriterion("discount not between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andShipFeeIsNull() {
            addCriterion("ship_fee is null");
            return (Criteria) this;
        }

        public Criteria andShipFeeIsNotNull() {
            addCriterion("ship_fee is not null");
            return (Criteria) this;
        }

        public Criteria andShipFeeEqualTo(BigDecimal value) {
            addCriterion("ship_fee =", value, "shipFee");
            return (Criteria) this;
        }

        public Criteria andShipFeeNotEqualTo(BigDecimal value) {
            addCriterion("ship_fee <>", value, "shipFee");
            return (Criteria) this;
        }

        public Criteria andShipFeeGreaterThan(BigDecimal value) {
            addCriterion("ship_fee >", value, "shipFee");
            return (Criteria) this;
        }

        public Criteria andShipFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ship_fee >=", value, "shipFee");
            return (Criteria) this;
        }

        public Criteria andShipFeeLessThan(BigDecimal value) {
            addCriterion("ship_fee <", value, "shipFee");
            return (Criteria) this;
        }

        public Criteria andShipFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ship_fee <=", value, "shipFee");
            return (Criteria) this;
        }

        public Criteria andShipFeeIn(List<BigDecimal> values) {
            addCriterion("ship_fee in", values, "shipFee");
            return (Criteria) this;
        }

        public Criteria andShipFeeNotIn(List<BigDecimal> values) {
            addCriterion("ship_fee not in", values, "shipFee");
            return (Criteria) this;
        }

        public Criteria andShipFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ship_fee between", value1, value2, "shipFee");
            return (Criteria) this;
        }

        public Criteria andShipFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ship_fee not between", value1, value2, "shipFee");
            return (Criteria) this;
        }

        public Criteria andRefidIsNull() {
            addCriterion("refid is null");
            return (Criteria) this;
        }

        public Criteria andRefidIsNotNull() {
            addCriterion("refid is not null");
            return (Criteria) this;
        }

        public Criteria andRefidEqualTo(Integer value) {
            addCriterion("refid =", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidNotEqualTo(Integer value) {
            addCriterion("refid <>", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidGreaterThan(Integer value) {
            addCriterion("refid >", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidGreaterThanOrEqualTo(Integer value) {
            addCriterion("refid >=", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidLessThan(Integer value) {
            addCriterion("refid <", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidLessThanOrEqualTo(Integer value) {
            addCriterion("refid <=", value, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidIn(List<Integer> values) {
            addCriterion("refid in", values, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidNotIn(List<Integer> values) {
            addCriterion("refid not in", values, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidBetween(Integer value1, Integer value2) {
            addCriterion("refid between", value1, value2, "refid");
            return (Criteria) this;
        }

        public Criteria andRefidNotBetween(Integer value1, Integer value2) {
            addCriterion("refid not between", value1, value2, "refid");
            return (Criteria) this;
        }

        public Criteria andDiscountPerIsNull() {
            addCriterion("discount_per is null");
            return (Criteria) this;
        }

        public Criteria andDiscountPerIsNotNull() {
            addCriterion("discount_per is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountPerEqualTo(Short value) {
            addCriterion("discount_per =", value, "discountPer");
            return (Criteria) this;
        }

        public Criteria andDiscountPerNotEqualTo(Short value) {
            addCriterion("discount_per <>", value, "discountPer");
            return (Criteria) this;
        }

        public Criteria andDiscountPerGreaterThan(Short value) {
            addCriterion("discount_per >", value, "discountPer");
            return (Criteria) this;
        }

        public Criteria andDiscountPerGreaterThanOrEqualTo(Short value) {
            addCriterion("discount_per >=", value, "discountPer");
            return (Criteria) this;
        }

        public Criteria andDiscountPerLessThan(Short value) {
            addCriterion("discount_per <", value, "discountPer");
            return (Criteria) this;
        }

        public Criteria andDiscountPerLessThanOrEqualTo(Short value) {
            addCriterion("discount_per <=", value, "discountPer");
            return (Criteria) this;
        }

        public Criteria andDiscountPerIn(List<Short> values) {
            addCriterion("discount_per in", values, "discountPer");
            return (Criteria) this;
        }

        public Criteria andDiscountPerNotIn(List<Short> values) {
            addCriterion("discount_per not in", values, "discountPer");
            return (Criteria) this;
        }

        public Criteria andDiscountPerBetween(Short value1, Short value2) {
            addCriterion("discount_per between", value1, value2, "discountPer");
            return (Criteria) this;
        }

        public Criteria andDiscountPerNotBetween(Short value1, Short value2) {
            addCriterion("discount_per not between", value1, value2, "discountPer");
            return (Criteria) this;
        }

        public Criteria andTypeidIsNull() {
            addCriterion("typeid is null");
            return (Criteria) this;
        }

        public Criteria andTypeidIsNotNull() {
            addCriterion("typeid is not null");
            return (Criteria) this;
        }

        public Criteria andTypeidEqualTo(String value) {
            addCriterion("typeid =", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotEqualTo(String value) {
            addCriterion("typeid <>", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidGreaterThan(String value) {
            addCriterion("typeid >", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidGreaterThanOrEqualTo(String value) {
            addCriterion("typeid >=", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLessThan(String value) {
            addCriterion("typeid <", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLessThanOrEqualTo(String value) {
            addCriterion("typeid <=", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLike(String value) {
            addCriterion("typeid like", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotLike(String value) {
            addCriterion("typeid not like", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidIn(List<String> values) {
            addCriterion("typeid in", values, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotIn(List<String> values) {
            addCriterion("typeid not in", values, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidBetween(String value1, String value2) {
            addCriterion("typeid between", value1, value2, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotBetween(String value1, String value2) {
            addCriterion("typeid not between", value1, value2, "typeid");
            return (Criteria) this;
        }

        public Criteria andBankidIsNull() {
            addCriterion("bankid is null");
            return (Criteria) this;
        }

        public Criteria andBankidIsNotNull() {
            addCriterion("bankid is not null");
            return (Criteria) this;
        }

        public Criteria andBankidEqualTo(Short value) {
            addCriterion("bankid =", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotEqualTo(Short value) {
            addCriterion("bankid <>", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidGreaterThan(Short value) {
            addCriterion("bankid >", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidGreaterThanOrEqualTo(Short value) {
            addCriterion("bankid >=", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidLessThan(Short value) {
            addCriterion("bankid <", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidLessThanOrEqualTo(Short value) {
            addCriterion("bankid <=", value, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidIn(List<Short> values) {
            addCriterion("bankid in", values, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotIn(List<Short> values) {
            addCriterion("bankid not in", values, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidBetween(Short value1, Short value2) {
            addCriterion("bankid between", value1, value2, "bankid");
            return (Criteria) this;
        }

        public Criteria andBankidNotBetween(Short value1, Short value2) {
            addCriterion("bankid not between", value1, value2, "bankid");
            return (Criteria) this;
        }

        public Criteria andTransidIsNull() {
            addCriterion("transid is null");
            return (Criteria) this;
        }

        public Criteria andTransidIsNotNull() {
            addCriterion("transid is not null");
            return (Criteria) this;
        }

        public Criteria andTransidEqualTo(Short value) {
            addCriterion("transid =", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidNotEqualTo(Short value) {
            addCriterion("transid <>", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidGreaterThan(Short value) {
            addCriterion("transid >", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidGreaterThanOrEqualTo(Short value) {
            addCriterion("transid >=", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidLessThan(Short value) {
            addCriterion("transid <", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidLessThanOrEqualTo(Short value) {
            addCriterion("transid <=", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidIn(List<Short> values) {
            addCriterion("transid in", values, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidNotIn(List<Short> values) {
            addCriterion("transid not in", values, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidBetween(Short value1, Short value2) {
            addCriterion("transid between", value1, value2, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidNotBetween(Short value1, Short value2) {
            addCriterion("transid not between", value1, value2, "transid");
            return (Criteria) this;
        }

        public Criteria andTranscauseidIsNull() {
            addCriterion("transcauseid is null");
            return (Criteria) this;
        }

        public Criteria andTranscauseidIsNotNull() {
            addCriterion("transcauseid is not null");
            return (Criteria) this;
        }

        public Criteria andTranscauseidEqualTo(Short value) {
            addCriterion("transcauseid =", value, "transcauseid");
            return (Criteria) this;
        }

        public Criteria andTranscauseidNotEqualTo(Short value) {
            addCriterion("transcauseid <>", value, "transcauseid");
            return (Criteria) this;
        }

        public Criteria andTranscauseidGreaterThan(Short value) {
            addCriterion("transcauseid >", value, "transcauseid");
            return (Criteria) this;
        }

        public Criteria andTranscauseidGreaterThanOrEqualTo(Short value) {
            addCriterion("transcauseid >=", value, "transcauseid");
            return (Criteria) this;
        }

        public Criteria andTranscauseidLessThan(Short value) {
            addCriterion("transcauseid <", value, "transcauseid");
            return (Criteria) this;
        }

        public Criteria andTranscauseidLessThanOrEqualTo(Short value) {
            addCriterion("transcauseid <=", value, "transcauseid");
            return (Criteria) this;
        }

        public Criteria andTranscauseidIn(List<Short> values) {
            addCriterion("transcauseid in", values, "transcauseid");
            return (Criteria) this;
        }

        public Criteria andTranscauseidNotIn(List<Short> values) {
            addCriterion("transcauseid not in", values, "transcauseid");
            return (Criteria) this;
        }

        public Criteria andTranscauseidBetween(Short value1, Short value2) {
            addCriterion("transcauseid between", value1, value2, "transcauseid");
            return (Criteria) this;
        }

        public Criteria andTranscauseidNotBetween(Short value1, Short value2) {
            addCriterion("transcauseid not between", value1, value2, "transcauseid");
            return (Criteria) this;
        }

        public Criteria andItemaspectidIsNull() {
            addCriterion("itemaspectid is null");
            return (Criteria) this;
        }

        public Criteria andItemaspectidIsNotNull() {
            addCriterion("itemaspectid is not null");
            return (Criteria) this;
        }

        public Criteria andItemaspectidEqualTo(Short value) {
            addCriterion("itemaspectid =", value, "itemaspectid");
            return (Criteria) this;
        }

        public Criteria andItemaspectidNotEqualTo(Short value) {
            addCriterion("itemaspectid <>", value, "itemaspectid");
            return (Criteria) this;
        }

        public Criteria andItemaspectidGreaterThan(Short value) {
            addCriterion("itemaspectid >", value, "itemaspectid");
            return (Criteria) this;
        }

        public Criteria andItemaspectidGreaterThanOrEqualTo(Short value) {
            addCriterion("itemaspectid >=", value, "itemaspectid");
            return (Criteria) this;
        }

        public Criteria andItemaspectidLessThan(Short value) {
            addCriterion("itemaspectid <", value, "itemaspectid");
            return (Criteria) this;
        }

        public Criteria andItemaspectidLessThanOrEqualTo(Short value) {
            addCriterion("itemaspectid <=", value, "itemaspectid");
            return (Criteria) this;
        }

        public Criteria andItemaspectidIn(List<Short> values) {
            addCriterion("itemaspectid in", values, "itemaspectid");
            return (Criteria) this;
        }

        public Criteria andItemaspectidNotIn(List<Short> values) {
            addCriterion("itemaspectid not in", values, "itemaspectid");
            return (Criteria) this;
        }

        public Criteria andItemaspectidBetween(Short value1, Short value2) {
            addCriterion("itemaspectid between", value1, value2, "itemaspectid");
            return (Criteria) this;
        }

        public Criteria andItemaspectidNotBetween(Short value1, Short value2) {
            addCriterion("itemaspectid not between", value1, value2, "itemaspectid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 07 16:39:41 CET 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}