package it.studiofontanelli.jabistudio.entity;

import java.math.BigDecimal;
import java.util.Date;

public class AbiMainPofR {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.id
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.poftid
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private Integer poftid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.itemid
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.uml
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private String uml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.umc
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private String umc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.mult
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private Short mult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.price
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.iva
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private Short iva;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.insert_date
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private Date insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.update_date
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.price_pricelist
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private BigDecimal pricePricelist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.offer
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private String offer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.note
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _abi_main_pof_r.qty
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    private Integer qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.id
     *
     * @return the value of _abi_main_pof_r.id
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.id
     *
     * @param id the value for _abi_main_pof_r.id
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.poftid
     *
     * @return the value of _abi_main_pof_r.poftid
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public Integer getPoftid() {
        return poftid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.poftid
     *
     * @param poftid the value for _abi_main_pof_r.poftid
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setPoftid(Integer poftid) {
        this.poftid = poftid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.itemid
     *
     * @return the value of _abi_main_pof_r.itemid
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.itemid
     *
     * @param itemid the value for _abi_main_pof_r.itemid
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.uml
     *
     * @return the value of _abi_main_pof_r.uml
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public String getUml() {
        return uml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.uml
     *
     * @param uml the value for _abi_main_pof_r.uml
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setUml(String uml) {
        this.uml = uml == null ? null : uml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.umc
     *
     * @return the value of _abi_main_pof_r.umc
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public String getUmc() {
        return umc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.umc
     *
     * @param umc the value for _abi_main_pof_r.umc
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setUmc(String umc) {
        this.umc = umc == null ? null : umc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.mult
     *
     * @return the value of _abi_main_pof_r.mult
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public Short getMult() {
        return mult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.mult
     *
     * @param mult the value for _abi_main_pof_r.mult
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setMult(Short mult) {
        this.mult = mult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.price
     *
     * @return the value of _abi_main_pof_r.price
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.price
     *
     * @param price the value for _abi_main_pof_r.price
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.iva
     *
     * @return the value of _abi_main_pof_r.iva
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public Short getIva() {
        return iva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.iva
     *
     * @param iva the value for _abi_main_pof_r.iva
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setIva(Short iva) {
        this.iva = iva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.insert_date
     *
     * @return the value of _abi_main_pof_r.insert_date
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.insert_date
     *
     * @param insertDate the value for _abi_main_pof_r.insert_date
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.update_date
     *
     * @return the value of _abi_main_pof_r.update_date
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.update_date
     *
     * @param updateDate the value for _abi_main_pof_r.update_date
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.price_pricelist
     *
     * @return the value of _abi_main_pof_r.price_pricelist
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public BigDecimal getPricePricelist() {
        return pricePricelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.price_pricelist
     *
     * @param pricePricelist the value for _abi_main_pof_r.price_pricelist
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setPricePricelist(BigDecimal pricePricelist) {
        this.pricePricelist = pricePricelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.offer
     *
     * @return the value of _abi_main_pof_r.offer
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public String getOffer() {
        return offer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.offer
     *
     * @param offer the value for _abi_main_pof_r.offer
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setOffer(String offer) {
        this.offer = offer == null ? null : offer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.note
     *
     * @return the value of _abi_main_pof_r.note
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.note
     *
     * @param note the value for _abi_main_pof_r.note
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _abi_main_pof_r.qty
     *
     * @return the value of _abi_main_pof_r.qty
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _abi_main_pof_r.qty
     *
     * @param qty the value for _abi_main_pof_r.qty
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}