package it.studiofontanelli.jabistudio.mapper;

import it.studiofontanelli.jabistudio.entity.AbiDocksDock;
import it.studiofontanelli.jabistudio.entity.AbiDocksDockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AbiDocksDockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    int countByExample(AbiDocksDockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    int deleteByExample(AbiDocksDockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    int insert(AbiDocksDock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    int insertSelective(AbiDocksDock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    List<AbiDocksDock> selectByExample(AbiDocksDockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    AbiDocksDock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    int updateByExampleSelective(@Param("record") AbiDocksDock record, @Param("example") AbiDocksDockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    int updateByExample(@Param("record") AbiDocksDock record, @Param("example") AbiDocksDockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    int updateByPrimaryKeySelective(AbiDocksDock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_docks_dock
     *
     * @mbggenerated Tue Mar 08 14:24:06 CET 2016
     */
    int updateByPrimaryKey(AbiDocksDock record);
}