package it.studiofontanelli.jabistudio.mapper;

import it.studiofontanelli.jabistudio.entity.AbiFormsForm;
import it.studiofontanelli.jabistudio.entity.AbiFormsFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AbiFormsFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int countByExample(AbiFormsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int deleteByExample(AbiFormsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int deleteByPrimaryKey(Integer idField);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int insert(AbiFormsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int insertSelective(AbiFormsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    List<AbiFormsForm> selectByExample(AbiFormsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    AbiFormsForm selectByPrimaryKey(Integer idField);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByExampleSelective(@Param("record") AbiFormsForm record, @Param("example") AbiFormsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByExample(@Param("record") AbiFormsForm record, @Param("example") AbiFormsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByPrimaryKeySelective(AbiFormsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_form
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByPrimaryKey(AbiFormsForm record);
}