package it.studiofontanelli.jabistudio.mapper;

import it.studiofontanelli.jabistudio.entity.AbiFormsDescr;
import it.studiofontanelli.jabistudio.entity.AbiFormsDescrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AbiFormsDescrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int countByExample(AbiFormsDescrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int deleteByExample(AbiFormsDescrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int deleteByPrimaryKey(Integer idForm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int insert(AbiFormsDescr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int insertSelective(AbiFormsDescr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    List<AbiFormsDescr> selectByExample(AbiFormsDescrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    AbiFormsDescr selectByPrimaryKey(Integer idForm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByExampleSelective(@Param("record") AbiFormsDescr record, @Param("example") AbiFormsDescrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByExample(@Param("record") AbiFormsDescr record, @Param("example") AbiFormsDescrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByPrimaryKeySelective(AbiFormsDescr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_forms_descr
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByPrimaryKey(AbiFormsDescr record);
}