package it.studiofontanelli.jabistudio.mapper;

import it.studiofontanelli.jabistudio.entity.AbiMainPofT;
import it.studiofontanelli.jabistudio.entity.AbiMainPofTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AbiMainPofTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    int countByExample(AbiMainPofTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    int deleteByExample(AbiMainPofTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    int insert(AbiMainPofT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    int insertSelective(AbiMainPofT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    List<AbiMainPofT> selectByExample(AbiMainPofTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    AbiMainPofT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    int updateByExampleSelective(@Param("record") AbiMainPofT record, @Param("example") AbiMainPofTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    int updateByExample(@Param("record") AbiMainPofT record, @Param("example") AbiMainPofTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    int updateByPrimaryKeySelective(AbiMainPofT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_t
     *
     * @mbggenerated Mon Mar 07 15:19:32 CET 2016
     */
    int updateByPrimaryKey(AbiMainPofT record);
}