package it.studiofontanelli.jabistudio.mapper;

import it.studiofontanelli.jabistudio.entity.AbiMainPofR;
import it.studiofontanelli.jabistudio.entity.AbiMainPofRExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AbiMainPofRMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int countByExample(AbiMainPofRExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int deleteByExample(AbiMainPofRExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int insert(AbiMainPofR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int insertSelective(AbiMainPofR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    List<AbiMainPofR> selectByExample(AbiMainPofRExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    AbiMainPofR selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByExampleSelective(@Param("record") AbiMainPofR record, @Param("example") AbiMainPofRExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByExample(@Param("record") AbiMainPofR record, @Param("example") AbiMainPofRExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByPrimaryKeySelective(AbiMainPofR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _abi_main_pof_r
     *
     * @mbggenerated Mon Mar 07 16:39:41 CET 2016
     */
    int updateByPrimaryKey(AbiMainPofR record);
}